project:
  type: website
  output-dir: _site

website:
  title: "Chunyu"                    # <-- CHANGE THIS
  description: "applied math in OSU" # <-- CHANGE THIS
  site-url: https://gugu-12.github.io  # <-- CHANGE THIS

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: posts.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/gugu-12  # <-- CHANGE THIS
      - icon: envelope
        href: mailto:gu.1204@buckeyemail.osu.edu  # <-- CHANGE THIS

  page-footer:
    center: |
      Built with [Quarto](https://quarto.org/) · © 2025 Your Name

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true

execute:
  freeze: auto
